// GENERATED by tools/gen-scene-map.ts -- do not edit by hand.
// Run: npm run scenes:map
//
// Premade scenes address models by numeric catalogue id; Poseify keys models
// by a semantic id. This table bridges them.
//
// Most entries resolve by FBX filename, which works even though the scenes
// reference the `*_OP_Y_IK.fbx` rig generation that now 403s: the same
// character exists as a reachable `*_OP_IK.fbx`, and the bone names
// (mixamorig*) are identical, so the pose data still applies.
//
// A small number of characters have no surviving FBX at all (the cartoon set,
// the mannequin frames, most quadrupeds). Those map to a hand-picked
// stand-in of the right body type and are marked "substituted" below, so a
// scene loads with a plausible figure instead of failing outright.

export interface SceneModelMapping {
  poseifyId: string;
  vendorName: string;
}

export const SCENE_MODEL_MAP: Record<string, SceneModelMapping> = {
  "4": { poseifyId: "mixamo_ybot", vendorName: "Bot Male" },
  "5": { poseifyId: "mixamo_xbot", vendorName: "Bot Female" },
  "6": { poseifyId: "mannequin_male", vendorName: "Mannequin Male" },
  "7": { poseifyId: "anime_female", vendorName: "Anime Female" },
  "8": { poseifyId: "realistic_muscular_male", vendorName: "Realistic Muscular Male" },
  "9": { poseifyId: "teen_female", vendorName: "Teen Fit Female" },
  "10": { poseifyId: "teen_male", vendorName: "Teen Fit Male" },
  "11": { poseifyId: "brute_male", vendorName: "Brute Male" },
  "12": { poseifyId: "muscular_female", vendorName: "Muscular Female" },
  "13": { poseifyId: "stocky_female", vendorName: "Stocky Female" },
  "14": { poseifyId: "stocky_male", vendorName: "Stocky Male" },
  "15": { poseifyId: "skinny_female", vendorName: "Skinny Female" },
  "16": { poseifyId: "realistic_woman", vendorName: "Realistic Woman" },
  "17": { poseifyId: "skinny_male", vendorName: "Skinny Male" },
  "18": { poseifyId: "anime_child_girl", vendorName: "Anime Child Girl" },
  "19": { poseifyId: "anime_child_boy", vendorName: "Anime Child Boy" },
  "20": { poseifyId: "bot_y", vendorName: "Bot Male" },
  "21": { poseifyId: "bot_x", vendorName: "Bot Female" },
  "22": { poseifyId: "male_young_teen", vendorName: "Male Young Teen" },
  "23": { poseifyId: "anime_curvy_female", vendorName: "Anime Curvy Female" },
  "24": { poseifyId: "anime_basic_male", vendorName: "Anime Basic Male" },
  "25": { poseifyId: "anime_basic_female", vendorName: "Anime Basic Female" },
  "26": { poseifyId: "anime_tall_curvy_female", vendorName: "Anime Tall Curvy Female" },
  "27": { poseifyId: "anime_tall_male", vendorName: "Anime Tall Male" },
  "28": { poseifyId: "skeleton", vendorName: "Skeleton" },
  "29": { poseifyId: "bot_y_fixed", vendorName: "Bot Male" },
  "30": { poseifyId: "bot_x_fixed", vendorName: "Bot Female" },
  "31": { poseifyId: "chibi_male", vendorName: "Chibi Male" },
  "32": { poseifyId: "zombie_alien", vendorName: "Zombie/Alien" },
  "33": { poseifyId: "horse", vendorName: "Horse" },
  "34": { poseifyId: "female_mermaid", vendorName: "Female Mermaid" },
  "35": { poseifyId: "male_mermaid", vendorName: "Male Mermaid" },
  "36": { poseifyId: "werewolf", vendorName: "Werewolf" },
  "37": { poseifyId: "horse", vendorName: "Wolf" }, // substituted: no surviving rig
  "38": { poseifyId: "mannequin_male", vendorName: "Mannequin Male" },
  "39": { poseifyId: "anime_female", vendorName: "Anime Female" },
  "40": { poseifyId: "realistic_muscular_male", vendorName: "Realistic Muscular Male" },
  "41": { poseifyId: "teen_female", vendorName: "Teen Fit Female" },
  "42": { poseifyId: "teen_male", vendorName: "Teen Fit Male" },
  "43": { poseifyId: "brute_male", vendorName: "Brute Male" },
  "44": { poseifyId: "muscular_female", vendorName: "Muscular Female" },
  "45": { poseifyId: "stocky_female", vendorName: "Stocky Female" },
  "46": { poseifyId: "stocky_male", vendorName: "Stocky Male" },
  "47": { poseifyId: "skinny_female", vendorName: "Skinny Female" },
  "48": { poseifyId: "realistic_woman", vendorName: "Realistic Woman" },
  "49": { poseifyId: "skinny_male", vendorName: "Skinny Male" },
  "50": { poseifyId: "anime_child_girl", vendorName: "Anime Child Girl" },
  "51": { poseifyId: "anime_child_boy", vendorName: "Anime Child Boy" },
  "52": { poseifyId: "male_young_teen", vendorName: "Male Young Teen" },
  "53": { poseifyId: "anime_curvy_female", vendorName: "Anime Curvy Female" },
  "54": { poseifyId: "anime_basic_male", vendorName: "Anime Basic Male" },
  "55": { poseifyId: "anime_basic_female", vendorName: "Anime Basic Female" },
  "56": { poseifyId: "anime_tall_curvy_female", vendorName: "Anime Tall Curvy Female" },
  "57": { poseifyId: "anime_tall_male", vendorName: "Anime Tall Male" },
  "58": { poseifyId: "skeleton", vendorName: "Skeleton" },
  "59": { poseifyId: "bot_y_fixed", vendorName: "Bot Male" },
  "60": { poseifyId: "bot_x_fixed", vendorName: "Bot Female" },
  "61": { poseifyId: "chibi_male", vendorName: "Chibi Male" },
  "62": { poseifyId: "zombie_alien", vendorName: "Zombie/Alien" },
  "63": { poseifyId: "mannequin_male", vendorName: "Male Mannequin Frame" }, // substituted: no surviving rig
  "64": { poseifyId: "bot_x", vendorName: "Blocky Bot" }, // substituted: no surviving rig
  "65": { poseifyId: "bot_x", vendorName: "Stick Bot" }, // substituted: no surviving rig
  "66": { poseifyId: "bot_x", vendorName: "Square Stick Bot" }, // substituted: no surviving rig
  "67": { poseifyId: "mannequin_male", vendorName: "Womannequin" }, // substituted: no surviving rig
  "68": { poseifyId: "realistic_muscular_male", vendorName: "Stylized Fit Male" }, // substituted: no surviving rig
  "69": { poseifyId: "skeleton", vendorName: "Male Simplified Skeleton" }, // substituted: no surviving rig
  "70": { poseifyId: "skeleton", vendorName: "Female Simplified Skeleton" }, // substituted: no surviving rig
  "71": { poseifyId: "skeleton", vendorName: "Female Mannequin Frame" }, // substituted: no surviving rig
  "72": { poseifyId: "mannequin_male", vendorName: "Female Mannequin Frame Curvy" }, // substituted: no surviving rig
  "73": { poseifyId: "realistic_muscular_male", vendorName: "Realistic Muscular Male with Face" }, // substituted: no surviving rig
  "74": { poseifyId: "anime_basic_male", vendorName: "Cartoon Male 1" }, // substituted: no surviving rig
  "75": { poseifyId: "anime_basic_female", vendorName: "Cartoon Female 1" }, // substituted: no surviving rig
  "76": { poseifyId: "anime_basic_male", vendorName: "Cartoon Male 2" }, // substituted: no surviving rig
  "77": { poseifyId: "anime_basic_female", vendorName: "Cartoon Female 2" }, // substituted: no surviving rig
  "78": { poseifyId: "anime_basic_male", vendorName: "Cartoon Male 3" }, // substituted: no surviving rig
  "79": { poseifyId: "anime_basic_female", vendorName: "Cartoon Female 3" }, // substituted: no surviving rig
  "80": { poseifyId: "anime_basic_male", vendorName: "Cartoon Male 4" }, // substituted: no surviving rig
  "81": { poseifyId: "brute_male", vendorName: "Brute Bot Male" }, // substituted: no surviving rig
  "82": { poseifyId: "horse", vendorName: "Bonnet Macaque" }, // substituted: no surviving rig
  "83": { poseifyId: "horse", vendorName: "Cat" }, // substituted: no surviving rig
  "84": { poseifyId: "horse", vendorName: "Bear" }, // substituted: no surviving rig
  "85": { poseifyId: "horse", vendorName: "Bull" }, // substituted: no surviving rig
  "86": { poseifyId: "horse", vendorName: "Cow" }, // substituted: no surviving rig
  "87": { poseifyId: "horse", vendorName: "Deer" }, // substituted: no surviving rig
  "88": { poseifyId: "horse", vendorName: "Kangaroo" }, // substituted: no surviving rig
};

/** Resolve a vendor numeric model id to a Poseify model id, if one exists. */
export function sceneModelPoseifyId(vendorId: number | string): string | undefined {
  return SCENE_MODEL_MAP[String(vendorId)]?.poseifyId;
}
